import { createServer } from 'node:http';
import { randomBytes } from 'node:crypto';
import { readFile,mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { workerConfig,providerEnvironment } from '../types';
import { connectionPage,type ConnectionState } from './connection-page';
const config=workerConfig.parse(JSON.parse(await readFile(process.argv[2]??'','utf8')));
const target=config.targets.find(t=>t.account_id===process.argv[3]&&t.provider==='anthropic');
if(!target)throw new Error('claude_account_not_configured');
const publicUrl=new URL(process.env.LOGIN_PUBLIC_URL??'');
if(publicUrl.protocol!=='https:'||publicUrl.pathname!=='/'||publicUrl.username||publicUrl.password||publicUrl.search||publicUrl.hash)throw new Error('LOGIN_PUBLIC_URL must be an HTTPS origin routed to this worker');
const port=Number(process.env.LOGIN_PORT??8787);
if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('invalid_port');
await mkdir(target.auth_dir,{recursive:true,mode:0o700});
const state:ConnectionState={status:'starting',submitted:false};
const token=randomBytes(32).toString('hex');
const child=spawn(target.binary,['auth','login','--claudeai'],{env:providerEnvironment(target),stdio:['pipe','pipe','pipe']});
let output='';
const collect=(data:Buffer)=>{
  output=(output+data.toString()).slice(-32000);
  const match=output.match(/https:\/\/(?:claude\.com|claude\.ai)\/[^\s\x07\x1b]+/);
  if(match){const url=new URL(match[0]);if(url.pathname.endsWith('/oauth/authorize')){state.authorization_url=url.toString();state.status='waiting';}}
};
child.stdout.on('data',collect);child.stderr.on('data',collect);
child.stdin.on('error',()=>{state.status='failed';});
child.on('error',()=>{state.status='failed';});
child.on('close',code=>{state.status=code===0?'complete':'failed';output='';});
const server=createServer(connectionPage(token,publicUrl.origin,state,code=>child.stdin.write(code+'\n')));
server.headersTimeout=10000;server.requestTimeout=15000;
server.listen(port,'127.0.0.1',()=>console.log(`Phone connection: ${publicUrl.origin}/connect/${token}\nExpires in 10 minutes. Keep this link private.`));
const stop=()=>{child.kill('SIGTERM');server.close();};
const timer=setTimeout(stop,600000);server.on('close',()=>clearTimeout(timer));server.on('error',stop);
process.on('SIGINT',stop);process.on('SIGTERM',stop);
