import {claude} from './claude';
import {codex} from './codex';
import {cursor} from './cursor';
import {gemini} from './gemini';
import type {Observer,ProviderName} from './types';
export * from './types';
export {diagnosticCode,diagnostics} from './http';
export {claude,codex,cursor,gemini};
export const observers:Record<ProviderName,Observer>={anthropic:claude,openai:codex,cursor,google:gemini};
export const observerFor=(provider:string):Observer|null=>(observers as Record<string,Observer|undefined>)[provider]??null;
